// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAzj09JnU9ZHwe87VUIHbVEWnG2YZghjE',
    appId: '1:691040399884:web:443d43fa81a98ac2f8f429',
    messagingSenderId: '691040399884',
    projectId: 'project2-a0553',
    authDomain: 'project2-a0553.firebaseapp.com',
    storageBucket: 'project2-a0553.firebasestorage.app',
    measurementId: 'G-ND7LHZPS6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhp7QUIqx1vVI23oaOfIEdhJfQedwoFqY',
    appId: '1:691040399884:android:aa53a68826b2cb8cf8f429',
    messagingSenderId: '691040399884',
    projectId: 'project2-a0553',
    storageBucket: 'project2-a0553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7KGyxDIMSKSbQppRz4sJWCscK1-LETKw',
    appId: '1:691040399884:ios:a36468339949ef57f8f429',
    messagingSenderId: '691040399884',
    projectId: 'project2-a0553',
    storageBucket: 'project2-a0553.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7KGyxDIMSKSbQppRz4sJWCscK1-LETKw',
    appId: '1:691040399884:ios:a36468339949ef57f8f429',
    messagingSenderId: '691040399884',
    projectId: 'project2-a0553',
    storageBucket: 'project2-a0553.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAzj09JnU9ZHwe87VUIHbVEWnG2YZghjE',
    appId: '1:691040399884:web:c681ffcc17b22a7ef8f429',
    messagingSenderId: '691040399884',
    projectId: 'project2-a0553',
    authDomain: 'project2-a0553.firebaseapp.com',
    storageBucket: 'project2-a0553.firebasestorage.app',
    measurementId: 'G-R6DD4YQ7LR',
  );
}
